# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.13
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import powerdns_client
from powerdns_client.api.stats_api import StatsApi  # noqa: E501
from powerdns_client.rest import ApiException


class TestStatsApi(unittest.TestCase):
    """StatsApi unit test stubs"""

    def setUp(self):
        self.api = powerdns_client.api.stats_api.StatsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_stats(self):
        """Test case for get_stats

        Query statistics.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
