# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import powerdns_client
from powerdns_client.models.autoprimary import Autoprimary  # noqa: E501
from powerdns_client.rest import ApiException


class TestAutoprimary(unittest.TestCase):
    """Autoprimary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAutoprimary(self):
        """Test Autoprimary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.autoprimary.Autoprimary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
