# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.13
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import powerdns_client
from powerdns_client.api.zonecryptokey_api import ZonecryptokeyApi  # noqa: E501
from powerdns_client.rest import ApiException


class TestZonecryptokeyApi(unittest.TestCase):
    """ZonecryptokeyApi unit test stubs"""

    def setUp(self):
        self.api = powerdns_client.api.zonecryptokey_api.ZonecryptokeyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_cryptokey(self):
        """Test case for create_cryptokey

        Creates a Cryptokey  # noqa: E501
        """
        pass

    def test_delete_cryptokey(self):
        """Test case for delete_cryptokey

        This method deletes a key specified by cryptokey_id.  # noqa: E501
        """
        pass

    def test_get_cryptokey(self):
        """Test case for get_cryptokey

        Returns all data about the CryptoKey, including the privatekey.  # noqa: E501
        """
        pass

    def test_list_cryptokeys(self):
        """Test case for list_cryptokeys

        Get all CryptoKeys for a zone, except the privatekey  # noqa: E501
        """
        pass

    def test_modify_cryptokey(self):
        """Test case for modify_cryptokey

        This method (de)activates a key from zone_name specified by cryptokey_id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
