# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.13
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import powerdns_client
from powerdns_client.models.simple_statistic_item import SimpleStatisticItem  # noqa: E501
from powerdns_client.rest import ApiException


class TestSimpleStatisticItem(unittest.TestCase):
    """SimpleStatisticItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimpleStatisticItem(self):
        """Test SimpleStatisticItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = powerdns_client.models.simple_statistic_item.SimpleStatisticItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
