# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.13
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import powerdns_client
from powerdns_client.models.record import Record  # noqa: E501
from powerdns_client.rest import ApiException


class TestRecord(unittest.TestCase):
    """Record unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecord(self):
        """Test Record"""
        # FIXME: construct object with mandatory attributes with example values
        # model = powerdns_client.models.record.Record()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
