# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Comment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content': 'str',
        'account': 'str',
        'modified_at': 'int'
    }

    attribute_map = {
        'content': 'content',
        'account': 'account',
        'modified_at': 'modified_at'
    }

    def __init__(self, content=None, account=None, modified_at=None):  # noqa: E501
        """Comment - a model defined in Swagger"""  # noqa: E501
        self._content = None
        self._account = None
        self._modified_at = None
        self.discriminator = None
        if content is not None:
            self.content = content
        if account is not None:
            self.account = account
        if modified_at is not None:
            self.modified_at = modified_at

    @property
    def content(self):
        """Gets the content of this Comment.  # noqa: E501

        The actual comment  # noqa: E501

        :return: The content of this Comment.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this Comment.

        The actual comment  # noqa: E501

        :param content: The content of this Comment.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def account(self):
        """Gets the account of this Comment.  # noqa: E501

        Name of an account that added the comment  # noqa: E501

        :return: The account of this Comment.  # noqa: E501
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this Comment.

        Name of an account that added the comment  # noqa: E501

        :param account: The account of this Comment.  # noqa: E501
        :type: str
        """

        self._account = account

    @property
    def modified_at(self):
        """Gets the modified_at of this Comment.  # noqa: E501

        Timestamp of the last change to the comment  # noqa: E501

        :return: The modified_at of this Comment.  # noqa: E501
        :rtype: int
        """
        return self._modified_at

    @modified_at.setter
    def modified_at(self, modified_at):
        """Sets the modified_at of this Comment.

        Timestamp of the last change to the comment  # noqa: E501

        :param modified_at: The modified_at of this Comment.  # noqa: E501
        :type: int
        """

        self._modified_at = modified_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Comment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Comment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
