# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TSIGKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'id': 'str',
        'algorithm': 'str',
        'key': 'str',
        'type': 'str'
    }

    attribute_map = {
        'name': 'name',
        'id': 'id',
        'algorithm': 'algorithm',
        'key': 'key',
        'type': 'type'
    }

    def __init__(self, name=None, id=None, algorithm=None, key=None, type=None):  # noqa: E501
        """TSIGKey - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._id = None
        self._algorithm = None
        self._key = None
        self._type = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if id is not None:
            self.id = id
        if algorithm is not None:
            self.algorithm = algorithm
        if key is not None:
            self.key = key
        if type is not None:
            self.type = type

    @property
    def name(self):
        """Gets the name of this TSIGKey.  # noqa: E501

        The name of the key  # noqa: E501

        :return: The name of this TSIGKey.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TSIGKey.

        The name of the key  # noqa: E501

        :param name: The name of this TSIGKey.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this TSIGKey.  # noqa: E501

        The ID for this key, used in the TSIGkey URL endpoint.  # noqa: E501

        :return: The id of this TSIGKey.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TSIGKey.

        The ID for this key, used in the TSIGkey URL endpoint.  # noqa: E501

        :param id: The id of this TSIGKey.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def algorithm(self):
        """Gets the algorithm of this TSIGKey.  # noqa: E501

        The algorithm of the TSIG key  # noqa: E501

        :return: The algorithm of this TSIGKey.  # noqa: E501
        :rtype: str
        """
        return self._algorithm

    @algorithm.setter
    def algorithm(self, algorithm):
        """Sets the algorithm of this TSIGKey.

        The algorithm of the TSIG key  # noqa: E501

        :param algorithm: The algorithm of this TSIGKey.  # noqa: E501
        :type: str
        """

        self._algorithm = algorithm

    @property
    def key(self):
        """Gets the key of this TSIGKey.  # noqa: E501

        The Base64 encoded secret key, empty when listing keys. MAY be empty when POSTing to have the server generate the key material  # noqa: E501

        :return: The key of this TSIGKey.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this TSIGKey.

        The Base64 encoded secret key, empty when listing keys. MAY be empty when POSTing to have the server generate the key material  # noqa: E501

        :param key: The key of this TSIGKey.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def type(self):
        """Gets the type of this TSIGKey.  # noqa: E501

        Set to \"TSIGKey\"  # noqa: E501

        :return: The type of this TSIGKey.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TSIGKey.

        Set to \"TSIGKey\"  # noqa: E501

        :param type: The type of this TSIGKey.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TSIGKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TSIGKey):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
